service: motorbike-shop
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1

constructs:
    greets-queue:
        type: queue
        worker:
            handler: ./sqs/greets/greetsWorker.handler

plugins:
  - serverless-esbuild
  - serverless-lift

functions:
  # healthz
  - ${file(./controllers/healthz/healthzGetController/function.yml)}
  # greets
  - ${file(./controllers/greets/greetSendController/function.yml)}


